### ISSUE TITLE
Float support?

### ISSUE THREAD

**Issue by filippog** [smira/go-statsd#14]
Hi!
thanks for this statsd golang client! I'm using it and noticed there's no support for float gauges/counters, is this something you'd be interested in having?

**Comment by smira** [comment]
yep, that sounds as good thing to have, I would rather see at as a separate method next to methods which process integers

**Comment by filippog** [comment]
Sounds good! I gave it a try for counters in #15, what do you think?

**Comment by smira** [comment]
v1.2.1 tagged, thanks!

Would like to add gauges support as well, or we should close this issue?

**Comment by filippog** [comment]
Turns out I overlooked `FGauge` initially! I'll close and thanks!
