### ISSUE TITLE
Closing a client with invalid host hangs forever

### ISSUE THREAD

**Issue by vthiery** [smira/go-statsd#19]
Hi!

I ran into a weird issue running this piece of code:
```go
package main

import (
	"log"

	"github.com/smira/go-statsd"
)

func main() {
	client := statsd.NewClient("BOOM:BOOM")
	if err := client.Close(); err != nil {
		log.Fatalf("could not close, but got error: %v", err)
	}
	log.Print("all good!")
}
```

It hangs forever (apparently) saying:
> [STATSD] 2019/05/15 18:33:38 [STATSD] Error connecting to server: dial udp: address udp/BOOM: unknown port

I would have expected `Close()` to return an error, maybe telling me the address is incorrect or that it cannot be resolved.

**Comment by smira** [comment]
confirmed, thanks for reporting!

**Comment by smira** [comment]
1.3.1 is published now with the fix

**Comment by vthiery** [comment]
> 1.3.1 is published now with the fix

Wow that was fast! Thanks a lot!
