### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by l0rda** [smira/go-statsd#2]
Hello,

yesterday i saw your keynote at GopherCon Russia 2018. Excellent work!

Please, add possibility to add tags, maybe as client Option:

[**InfluxDB tag format:**](https://influxdb.com/blog/2015/11/03/getting_started_with_influx_statsd.html)  `,tag1=payroll,region=us-west`

[**Datadog tag format:**](http://docs.datadoghq.com/guides/dogstatsd/#datagram-format) `|#tag1:value1,tag2:value2`

It's boring to write every time `c.incr('some.data,rack=v6,region=eu,switch=12')` ;)

Thanks!

**Comment by smira** [comment]
Thanks, makes perfect sense for me, I will get it implemented!

**Comment by smira** [comment]
First implementation in #6, some tests and docs are missing
