### ISSUE TITLE
Compatibility with Brubeck

### ISSUE THREAD

**Issue by forward32** [smira/go-statsd#21]
Hi,

Is `go-statsd` compatible with brubeck (https://github.com/github/brubeck)?
It seems like counters work well, but other types of metrics (gauge, timers) not.

**Comment by smira** [comment]
Do you have any sample of the request which doesn't work?

go-statsd should emit metrics according to the spec, but there might be some subtle issues.

**Comment by smira** [comment]
There are some samples in the tests: https://github.com/smira/go-statsd/blob/master/client_test.go#L97

**Comment by forward32** [comment]
I suppose that maybe the problem with network on my side.
I will check it next week and will be back with results.

Thanks for reply!

**Comment by forward32** [comment]
Hi there!

I have tested it again and found problem on my side in the brubeck.
This library generates correct outgoing data, so issue is closed now, thanks.
