### ISSUE TITLE
Okmeter tag format

### ISSUE THREAD

**Issue by doc-sheet** [smira/go-statsd#33]
Hello!
Could you add an [okmeter](https://okmeter.io/misc/docs#statsd-plugin-config) tag support?
I guess I can't simply use basic TagFormat because separator is a string `_is_`

**Comment by smira** [comment]
Looks like tags are sent as part of the metric name, so the library itself doesn't have to be changed?

You can just send `"value.tag_is_value"` and everything is good? If needed, you can make a wrapper for syntactic sugar?

**Comment by smira** [comment]
if you have a PR, I could take a look. Please keep in mind it should be optimized for low memory allocations in either case.
